import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const read=(path)=>readFile(new URL(`../../${path}`,import.meta.url),'utf8');
test('dashboard refreshes identity and validates uploads',async()=>{const source=`${await read('dashboard.html')}\n${await read('assets/js/dashboard.js').catch(()=> '')}\n${await read('assets/js/dashboard-app.js').catch(()=> '')}`;assert.match(source,/auth\.getUser\(\)/);assert.match(source,/5\s*\*\s*1024\s*\*\s*1024/);assert.match(source,/image\/jpeg/);assert.match(source,/image\/png/);assert.match(source,/image\/webp/);assert.match(source,/storage\.from\(['"]Avatars['"]\)\.remove/)});
test('dashboard writes stay owner-filtered and helpers avoid HTML sinks',async()=>{const html=await read('dashboard.html');const js=`${await read('assets/js/dashboard.js').catch(()=> '')}\n${await read('assets/js/dashboard-app.js').catch(()=> '')}`;assert.match(js,/\.eq\(['"]user_id['"],\s*currentUser\.id\)/);assert.match(js,/path=`\$\{currentUser\.id\}\//);assert.match(js,/path\.startsWith\(`\$\{currentUser\.id\}\//);assert.doesNotMatch(js,/innerHTML\s*=/);assert.match(html,/assets\/js\/dashboard\.js/)});
test('dashboard exposes one professional editing workspace',async()=>{const html=await read('dashboard.html');assert.equal((html.match(/id="dashboard-form"/g)||[]).length,1);for(const id of ['card-canvas','save-profile','stat-views','stat-clicks','direct-card-editor'])assert.match(html,new RegExp(`id="${id}"`));assert.doesNotMatch(html,/\son(?:click|change|input)=/i)});
test('dashboard loads separated application modules',async()=>{const html=await read('dashboard.html');for(const file of ['dashboard.js','card-utils.js','icon-picker.js','card-view.js','dashboard-editor.js','dashboard-app.js'])assert.match(html,new RegExp(`assets/js/${file.replace('.','\\.')}`))});
test('image replacement is deferred until save, uses unique paths and cleans old storage',async()=>{const js=await read('assets/js/dashboard-app.js');const select=js.indexOf('function selectImage'),upload=js.indexOf(".upload(path"),save=js.indexOf('async function saveProfile');assert.ok(select>=0&&upload>select&&save>upload);assert.match(js,/pendingImages/);assert.match(js,/\$\{kind\}-\$\{Date\.now\(\)\}/);assert.match(js,/URL\.revokeObjectURL\(item\.url\)/);assert.match(js,/\.remove\(\[old\]\)/)});
